# refs: https://www.chromatic.com/docs/github-actions
name: Chromatic

on:
  push:
    branches:
      - main
    # TODO: build and upload only when components are modified.

env:
  CI: true
  NODE_VERSION: 18

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Node.js 16x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm i -g pnpm@7.27.0 && pnpm i --frozen-lockfile

      - name: install chromatic-cli
        run: npm i -g chromatic@next

      - name: Publish to Chromatic
        run: chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes --build-script-name="build"
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
